import Provider from './components/Provider'
import Navbar from './components/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'
import CreateProject from './components/CreateProject'
import { LocalizationProvider } from '@mui/x-date-pickers'
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
// @ts-ignore
export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      className={`${inter.className} h-full scroll-smooth antialiased`}
    >
      <body className='flex h-full flex-row bg-[#eceff180] p-[1rem]'>
        <Provider>
          <Navbar />
          <main className='grow'>{children}</main>

        </Provider>
      </body>
    </html>
  )
}
